# Generated by Django 3.0 on 2020-06-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawimage',
            name='name',
            field=models.CharField(default='Raw image', max_length=20),
        ),
        migrations.AddField(
            model_name='transformedimage',
            name='name',
            field=models.CharField(default='Transformed image', max_length=20),
        ),
    ]
